name: dev workflow

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        name: [ release ]

    runs-on: ${{ matrix.os }}

    steps:
      # checkout
      # build
      - name: compile
        run: |
          echo "dev............."


      # unit test

      # create or update release
